### ISSUE TITLE
Update Profile - single entity update crashes the app

### ISSUE THREAD

**Issue by kkhetarpal** [Alok-Sharma/Stash#66]
When trying to update single entity in update profile, the app crashes with this error

 java.lang.StringIndexOutOfBoundsException: length=5; regionStart=0; regionLength=-1
            at java.lang.String.startEndAndLength(String.java:298)
            at java.lang.String.substring(String.java:1087)
            at aloksharma.ufl.edu.stash.ServerAccess.updateprofile(ServerAccess.java:261)
            at aloksharma.ufl.edu.stash.ServerAccess.onHandleIntent(ServerAccess.java:65)

To Do : If no field is entered, it should be ensured, previous fetched values are valid and updated.

**Comment by kkhetarpal** [comment]
Fixed at 5f987c62f84376b2563218391709236bdf812aa8
Relevant checks added.
